import js from '@eslint/js';
import pluginVue from 'eslint-plugin-vue';
import tseslint from 'typescript-eslint';

// Flat-config ESLint setup for the starter kit's Vue 3 + TypeScript frontend.
// `npm run lint` (eslint resources) uses this; tune the `rules` block to taste.
export default tseslint.config(
    {
        // Generated / build output — never lint these.
        ignores: [
            'resources/js/wayfinder/**',
            'resources/js/routes/**',
            'resources/js/actions/**',
            '**/*.d.ts',
            'public/**',
            'bootstrap/ssr/**',
        ],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    ...pluginVue.configs['flat/strongly-recommended'],
    {
        // Globals injected at build time by `unplugin-auto-import` (vue +
        // @vueuse/core, see vite.config.ts) plus standard browser/DOM APIs, so
        // that `no-undef` does not flag identifiers that exist at runtime.
        languageOptions: {
            globals: {
                // Vue Composition API (auto-imported)
                ref: 'readonly',
                computed: 'readonly',
                reactive: 'readonly',
                readonly: 'readonly',
                watch: 'readonly',
                watchEffect: 'readonly',
                watchPostEffect: 'readonly',
                watchSyncEffect: 'readonly',
                onMounted: 'readonly',
                onUnmounted: 'readonly',
                onBeforeMount: 'readonly',
                onBeforeUnmount: 'readonly',
                onUpdated: 'readonly',
                onBeforeUpdate: 'readonly',
                onActivated: 'readonly',
                onDeactivated: 'readonly',
                onErrorCaptured: 'readonly',
                onRenderTracked: 'readonly',
                onRenderTriggered: 'readonly',
                onServerPrefetch: 'readonly',
                nextTick: 'readonly',
                provide: 'readonly',
                inject: 'readonly',
                toRef: 'readonly',
                toRefs: 'readonly',
                toValue: 'readonly',
                unref: 'readonly',
                isRef: 'readonly',
                shallowRef: 'readonly',
                shallowReactive: 'readonly',
                shallowReadonly: 'readonly',
                triggerRef: 'readonly',
                customRef: 'readonly',
                markRaw: 'readonly',
                toRaw: 'readonly',
                effectScope: 'readonly',
                getCurrentScope: 'readonly',
                onScopeDispose: 'readonly',
                getCurrentInstance: 'readonly',
                defineComponent: 'readonly',
                defineAsyncComponent: 'readonly',
                h: 'readonly',
                useSlots: 'readonly',
                useAttrs: 'readonly',
                useId: 'readonly',
                useTemplateRef: 'readonly',
                useModel: 'readonly',
                useCssModule: 'readonly',
                useCssVars: 'readonly',
                // Browser + DOM
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                location: 'readonly',
                console: 'readonly',
                fetch: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                FormData: 'readonly',
                Blob: 'readonly',
                File: 'readonly',
                FileReader: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                HTMLElement: 'readonly',
                HTMLInputElement: 'readonly',
                Event: 'readonly',
                CustomEvent: 'readonly',
                MutationObserver: 'readonly',
                ResizeObserver: 'readonly',
                IntersectionObserver: 'readonly',
                matchMedia: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                MouseEvent: 'readonly',
                DragEvent: 'readonly',
                KeyboardEvent: 'readonly',
                ClipboardEvent: 'readonly',
                BeforeUnloadEvent: 'readonly',
                FileList: 'readonly',
                XMLHttpRequest: 'readonly',
                Image: 'readonly',
                EventTarget: 'readonly',
                HTMLDivElement: 'readonly',
                HTMLScriptElement: 'readonly',
                // VueUse (auto-imported)
                useEventListener: 'readonly',
                useDebounceFn: 'readonly',
                refDebounced: 'readonly',
            },
        },
    },
    {
        files: ['**/*.vue'],
        languageOptions: {
            parserOptions: {
                parser: tseslint.parser,
            },
        },
    },
    {
        rules: {
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-unused-vars': [
                'warn',
                { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
            ],
            'vue/multi-word-component-names': 'off',
        },
    },
);
